张量是一种专门的数据结构，与数组和矩阵非常相似。在 PyTorch 中，我们使用张量对模型的输入和输出以及模型的参数进行编码。


张量类似于 NumPy 的 ndarrays，不同之处在于张量可以在 GPU 或其他硬件加速器上运行。事实上，张量和 NumPy 数组通常可以共享相同的底层内存，无需复制数据。张量还针对自动微分进行了优化（我们将在后面的 Autograd 部分）。

In [5]:
import torch
import numpy as np

In [7]:
# 张量可以通过多种方式初始化。
# 张量可以直接从数据创建。自动推断数据类型。
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [9]:
x_data

tensor([[1, 2],
        [3, 4]])

In [13]:
# 张量可以直接从数据创建。自动推断数据类型。
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [15]:
# 从另一个张量创建张量
x_ones = torch.ones_like(x_data)
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [19]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[0.8034, 0.2881],
        [0.6339, 0.3431]])


In [23]:
# shape 是张量维度的元组。在下面的函数中，它确定输出张量的维数
shape = (3, 4,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.8190, 0.8788, 0.9915, 0.8425],
        [0.1645, 0.8004, 0.7182, 0.4139],
        [0.5481, 0.3681, 0.2769, 0.2026]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


## 张量的属性

In [28]:
# 张量属性描述它们的形状、数据类型和存储它们的设备。
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 张量的运算

In [38]:
# 张量运算，包括算术、线性代数、矩阵作（转置、索引、切片）、采样等。
# 每一个都可以在 CPU 和加速器上运行 例如 CUDA、MPS、MTIA 或 XPU
# 默认情况下，张量是在 CPU 上创建的。我们需要使用 .to 方法（在检查加速器可用性后）。

# 检查我们当前CUDA是否可用
print(torch.cuda.is_available())


# 将数据转移至加速设备上
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
print(tensor)

False
tensor([[0.1590, 0.0383, 0.9113, 0.2132],
        [0.6725, 0.7725, 0.5913, 0.0305],
        [0.0864, 0.7411, 0.7981, 0.9779]])


In [42]:
# 和uNmpy类似的索引和切片：
tensor = torch.ones(4,4)
print(tensor)
print(tensor[0])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([1., 1., 1., 1.])


In [44]:
print(tensor[:,0])

tensor([1., 1., 1., 1.])


In [46]:
tensor[...,-1]

tensor([1., 1., 1., 1.])

In [48]:
tensor[:,1] = 0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [52]:
# 连接张量可以使用 torch.cat 沿给定维度连接一系列张量
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
